// @ts-nocheck
// This file was generated by `tauri-specta`. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listCaptures() : Promise<Result<Capture[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_captures") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCapture(capture: NewCapture) : Promise<Result<Capture, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_capture", { capture }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createMediaCapture(bytesBase64: string, mime: string, kind: string, source: string, body: string) : Promise<Result<Capture, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_media_capture", { bytesBase64, mime, kind, source, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createMediaCaptureFromPath(path: string, source: string, body: string) : Promise<Result<Capture, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_media_capture_from_path", { path, source, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDroppedImagePreview(path: string) : Promise<Result<DroppedImagePreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dropped_image_preview", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async quickLookImage(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("quick_look_image", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCaptureBody(id: string, body: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_capture_body", { id, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCaptureTags(id: string, tags: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_capture_tags", { id, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCaptureDone(id: string, done: boolean, doneAt: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_capture_done", { id, done, doneAt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCaptureStatus(id: string, status: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_capture_status", { id, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async purgeExpiredDone(cutoffMs: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_expired_done", { cutoffMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCapture(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_capture", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAllCaptures() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_captures") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async seedDemoCaptures(seed: NewCapture[]) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("seed_demo_captures", { seed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async captureNow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("capture_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async capturePermissionStatus() : Promise<PermissionStatus> {
    return await TAURI_INVOKE("capture_permission_status");
},
async requestAccessibilityPermission() : Promise<PermissionStatus> {
    return await TAURI_INVOKE("request_accessibility_permission");
},
async requestInputMonitoringPermission() : Promise<PermissionStatus> {
    return await TAURI_INVOKE("request_input_monitoring_permission");
},
async ingestCapture(body: string, source: string) : Promise<Result<CaptureNotice, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ingest_capture", { body, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Capture = { id: string; body: string; source: string; section: string; tags: string[]; done: boolean; doneAt: number | null; createdAt: number; kind: string; imagePath: string | null; inProgress: boolean }
export type CaptureNotice = { id: string; body: string; source: string }
export type DroppedImagePreview = { bytesBase64: string; mime: string }
export type NewCapture = { id: string; body: string; source: string; section: string; tags: string[]; createdAt: number; done?: boolean; doneAt?: number | null; kind?: string; imagePath?: string | null; inProgress?: boolean }
export type PermissionStatus = { accessibility: boolean; inputMonitoring: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
