mod capture;
mod db;
#[cfg(target_os = "macos")]
#[path = "quick-look.rs"]
mod quick_look;

use db::Db;
use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri::{
    menu::{Menu, MenuItem},
    tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
    Manager, RunEvent, WindowEvent,
};
use tauri_specta::{collect_commands, Builder};

fn show_main_window(app: &tauri::AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.unminimize();
        let _ = window.show();
        let _ = window.set_focus();
    }
}

fn specta_builder() -> Builder {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        db_commands::list_captures,
        db_commands::create_capture,
        db_commands::create_media_capture,
        db_commands::create_media_capture_from_path,
        db_commands::get_dropped_image_preview,
        db_commands::quick_look_image,
        db_commands::update_capture_body,
        db_commands::update_capture_tags,
        db_commands::set_capture_done,
        db_commands::set_capture_status,
        db_commands::purge_expired_done,
        db_commands::delete_capture,
        db_commands::clear_all_captures,
        db_commands::seed_demo_captures,
        capture::capture_now,
        capture::capture_permission_status,
        capture::request_accessibility_permission,
        capture::request_input_monitoring_permission,
        capture::ingest_capture,
    ])
}

fn export_typescript_bindings(builder: &Builder) {
    builder
        .export(
            Typescript::default()
                .header(
                    "// @ts-nocheck\n// This file was generated by `tauri-specta`. Do not edit.\n",
                )
                // Timestamps/counts fit JS number; avoid bigint friction in the UI layer.
                .bigint(BigIntExportBehavior::Number),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export typescript bindings");
}

/// Enable macOS WKWebView "Check Spelling While Typing" (red underlines).
/// Must run before the webview is created or it only takes effect on the next launch.
#[cfg(target_os = "macos")]
fn enable_macos_spellcheck() {
    use objc2_foundation::{NSString, NSUserDefaults};

    let defaults = NSUserDefaults::standardUserDefaults();
    let key = NSString::from_str("WebContinuousSpellCheckingEnabled");
    defaults.setBool_forKey(true, &key);
    let _ = defaults.synchronize();
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let specta = specta_builder();

    #[cfg(debug_assertions)]
    export_typescript_bindings(&specta);

    // Before Builder creates the webview — see WebContinuousSpellCheckingEnabled notes above.
    #[cfg(target_os = "macos")]
    enable_macos_spellcheck();

    tauri::Builder::default()
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(
            tauri_plugin_global_shortcut::Builder::new()
                .with_handler(|app, _shortcut, event| {
                    capture::shortcut_handler(app, event.state);
                })
                .build(),
        )
        .invoke_handler(specta.invoke_handler())
        .setup(|app| {
            let data_dir = app.path().app_data_dir().map_err(|e| e.to_string())?;
            std::fs::create_dir_all(&data_dir).map_err(|e| e.to_string())?;
            let db_path = data_dir.join("toudou.sqlite3");
            let conn = db::open(&db_path)?;
            app.manage(Db(std::sync::Mutex::new(conn)));

            let show = MenuItem::with_id(app, "show", "Show toudou", true, None::<&str>)?;
            let quit = MenuItem::with_id(app, "quit", "Quit", true, None::<&str>)?;
            let menu = Menu::with_items(app, &[&show, &quit])?;

            let _tray = TrayIconBuilder::new()
                .icon(app.default_window_icon().unwrap().clone())
                .menu(&menu)
                .tooltip("toudou")
                .on_menu_event(|app, event| match event.id.as_ref() {
                    "show" => show_main_window(app),
                    "quit" => app.exit(0),
                    _ => {}
                })
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        show_main_window(tray.app_handle());
                    }
                })
                .build(app)?;

            capture::start(app.handle());
            Ok(())
        })
        .on_window_event(|window, event| {
            if let WindowEvent::CloseRequested { api, .. } = event {
                api.prevent_close();
                let _ = window.hide();
            }
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|app, event| match event {
            #[cfg(target_os = "macos")]
            RunEvent::Reopen {
                has_visible_windows: false,
                ..
            } => show_main_window(app),
            RunEvent::ExitRequested { api, code, .. } if code.is_none() => api.prevent_exit(),
            _ => {}
        });
}

mod db_commands {
    use crate::db::{self, Capture, Db, NewCapture};
    use base64::{engine::general_purpose::STANDARD, Engine as _};
    use serde::Serialize;
    use specta::Type;
    use tauri::{AppHandle, Manager};
    use uuid::Uuid;

    const MAX_IMAGE_PREVIEW_BYTES: u64 = 12 * 1024 * 1024;

    #[derive(Serialize, Type)]
    #[serde(rename_all = "camelCase")]
    pub struct DroppedImagePreview {
        pub bytes_base64: String,
        pub mime: String,
    }

    fn persist_media_capture(
        app: &AppHandle,
        state: &tauri::State<'_, Db>,
        bytes: Vec<u8>,
        mime: &str,
        kind: &str,
        source: String,
        body: String,
    ) -> Result<Capture, String> {
        if bytes.is_empty() {
            return Err("empty media attachment".into());
        }
        if !matches!(kind, "image" | "video") {
            return Err("invalid media kind".into());
        }
        if !mime.starts_with(&format!("{kind}/")) {
            return Err("media type does not match its kind".into());
        }

        let data_dir = app.path().app_data_dir().map_err(|e| e.to_string())?;
        let attachments = data_dir.join("attachments");
        std::fs::create_dir_all(&attachments).map_err(|e| e.to_string())?;

        let id = Uuid::new_v4().to_string();
        let ext = db::extension_for_mime(mime);
        let path = attachments.join(format!("{id}.{ext}"));
        std::fs::write(&path, &bytes).map_err(|e| e.to_string())?;

        let capture = NewCapture {
            id: id.clone(),
            body,
            source,
            section: "inbox".to_string(),
            tags: vec![],
            created_at: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_millis() as i64)
                .unwrap_or(0),
            done: false,
            done_at: None,
            kind: kind.to_string(),
            image_path: Some(path.to_string_lossy().into_owned()),
            in_progress: false,
        };

        let conn = state.0.lock().map_err(|e| e.to_string())?;
        db::create_capture(&conn, &capture)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn list_captures(state: tauri::State<'_, Db>) -> Result<Vec<Capture>, String> {
        let conn = state.0.lock().map_err(|e| e.to_string())?;
        db::list_captures(&conn)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn create_capture(
        state: tauri::State<'_, Db>,
        capture: NewCapture,
    ) -> Result<Capture, String> {
        let conn = state.0.lock().map_err(|e| e.to_string())?;
        db::create_capture(&conn, &capture)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn create_media_capture(
        app: AppHandle,
        state: tauri::State<'_, Db>,
        bytes_base64: String,
        mime: String,
        kind: String,
        source: String,
        body: String,
    ) -> Result<Capture, String> {
        let bytes = STANDARD
            .decode(bytes_base64.trim())
            .map_err(|e| e.to_string())?;
        persist_media_capture(&app, &state, bytes, &mime, &kind, source, body)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn create_media_capture_from_path(
        app: AppHandle,
        state: tauri::State<'_, Db>,
        path: String,
        source: String,
        body: String,
    ) -> Result<Capture, String> {
        let path = std::path::PathBuf::from(path);
        let (kind, mime) = db::media_metadata_for_path(&path)
            .ok_or_else(|| "unsupported media attachment".to_string())?;
        let bytes = std::fs::read(&path).map_err(|e| e.to_string())?;
        persist_media_capture(&app, &state, bytes, mime, kind, source, body)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn get_dropped_image_preview(path: String) -> Result<DroppedImagePreview, String> {
        let path = std::path::PathBuf::from(path);
        let (kind, mime) = db::media_metadata_for_path(&path)
            .ok_or_else(|| "unsupported media attachment".to_string())?;
        if kind != "image" {
            return Err("previews are only available for images".to_string());
        }
        let size = std::fs::metadata(&path).map_err(|e| e.to_string())?.len();
        if size > MAX_IMAGE_PREVIEW_BYTES {
            return Err("image preview is limited to 12 MB".to_string());
        }
        let bytes = std::fs::read(&path).map_err(|e| e.to_string())?;
        Ok(DroppedImagePreview {
            bytes_base64: STANDARD.encode(bytes),
            mime: mime.to_string(),
        })
    }

    #[tauri::command]
    #[specta::specta]
    pub fn quick_look_image(app: AppHandle, path: String) -> Result<(), String> {
        let path = std::path::PathBuf::from(path);
        let (kind, _) = db::media_metadata_for_path(&path)
            .ok_or_else(|| "unsupported media attachment".to_string())?;
        if kind != "image" {
            return Err("Quick Look is only available for images".to_string());
        }

        #[cfg(target_os = "macos")]
        app.run_on_main_thread(move || crate::quick_look::show(&path))
            .map_err(|e| e.to_string())?;

        #[cfg(not(target_os = "macos"))]
        let _ = app;
        Ok(())
    }

    #[tauri::command]
    #[specta::specta]
    pub fn update_capture_body(
        state: tauri::State<'_, Db>,
        id: String,
        body: String,
    ) -> Result<(), String> {
        let conn = state.0.lock().map_err(|e| e.to_string())?;
        db::update_body(&conn, &id, &body)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn update_capture_tags(
        state: tauri::State<'_, Db>,
        id: String,
        tags: Vec<String>,
    ) -> Result<(), String> {
        let conn = state.0.lock().map_err(|e| e.to_string())?;
        db::update_tags(&conn, &id, &tags)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn set_capture_done(
        state: tauri::State<'_, Db>,
        id: String,
        done: bool,
        done_at: Option<i64>,
    ) -> Result<(), String> {
        let conn = state.0.lock().map_err(|e| e.to_string())?;
        db::set_done(&conn, &id, done, done_at)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn set_capture_status(
        state: tauri::State<'_, Db>,
        id: String,
        status: String,
    ) -> Result<(), String> {
        let conn = state.0.lock().map_err(|e| e.to_string())?;
        db::set_status(&conn, &id, &status)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn purge_expired_done(
        state: tauri::State<'_, Db>,
        cutoff_ms: i64,
    ) -> Result<usize, String> {
        let conn = state.0.lock().map_err(|e| e.to_string())?;
        db::purge_done_before(&conn, cutoff_ms)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn delete_capture(state: tauri::State<'_, Db>, id: String) -> Result<(), String> {
        let conn = state.0.lock().map_err(|e| e.to_string())?;
        db::delete_capture(&conn, &id)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn clear_all_captures(state: tauri::State<'_, Db>) -> Result<usize, String> {
        let conn = state.0.lock().map_err(|e| e.to_string())?;
        db::clear_all_captures(&conn)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn seed_demo_captures(
        state: tauri::State<'_, Db>,
        seed: Vec<NewCapture>,
    ) -> Result<bool, String> {
        let conn = state.0.lock().map_err(|e| e.to_string())?;
        db::seed_if_empty(&conn, &seed)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn export_typescript_bindings_file() {
        export_typescript_bindings(&specta_builder());
    }
}
